version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: paloma_licitera
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  paloma-app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=paloma_licitera
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres123
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml
    command: python src/api.py

  scheduler:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=paloma_licitera
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres123
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml
    command: python -m src.scheduler daemon --interval 3600
    restart: unless-stopped

volumes:
  postgres_data: